#!/usr/bin/env ansible-playbook
---
# Configures SecureDrop dotfiles persistence on Admin and Journalist
# Workstations. Should be run after the servers have been installed.
- name: Configure Tails workstation.
  hosts: localhost
  connection: local
  gather_facts: yes
  roles:
    - role: tails-config
      tags: tails-config
