---
- name: Perform safe upgrade to ensure all the packages are updated.
  apt:
    upgrade: safe
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - apt
    - apt-upgrade

- name: Check if reboot is required due to security updates.
  stat:
    path: /var/run/reboot-required
  register: reboot_required
  # Task is read-only, so don't mark changed.
  changed_when: false
  tags:
    - reboot

- name: Reboot if required due to security updates.
  command: reboot
  when: reboot_required.stat.exists
  tags:
    - reboot

- name: Wait for server to come back.
  local_action:
    # action/local_action modules don't support
    # dict-style arg declaration, so use 'key=value' syntax
    module: wait_for
      host={{ ansible_ssh_host }}
      port={{ ansible_ssh_port }}
      delay=20
      state=started
  when: reboot_required.stat.exists
  # Wait action runs on localhost, and does NOT require sudo.
  sudo: false
  tags:
    - reboot
