---
- name: Install pip dependencies for running the unit and functional tests.
  pip:
    requirements: "{{ test_pip_requirements }}"
  tags:
    - pip

- name: Install testing package dependencies.
  apt:
    name: "{{ item }}"
    state: latest
  with_items: test_apt_dependencies
  tags:
    - apt

# Selenium 3 requires the installation of the Mozilla geckodriver.
- name: Check if geckodriver is downloaded.
  stat: path=/home/vagrant/geckodriver-v0.14.0-linux64.tar.gz
  sudo: no
  register: gecko_download
  tags:
    - apt

- name: Download geckodriver.
  sudo: no
  get_url:
    dest: /home/vagrant
    url: https://github.com/mozilla/geckodriver/releases/download/v0.14.0/geckodriver-v0.14.0-linux64.tar.gz
    sha256sum: aaae25e9197360261f966f6129b47ebdf75ee9da63c74c9f39397b1100cd9653
  when: gecko_download.stat.exists == False
  tags:
    - apt

- name: Check if geckodriver is installed.
  stat: path=/usr/local/bin/geckodriver
  sudo: no
  register: geckodriver
  tags:
    - apt

- name: Install geckodriver for the Selenium functional tests.
  unarchive:
    src: /home/vagrant/geckodriver-v0.14.0-linux64.tar.gz
    dest: /usr/local/bin/
    remote_src: yes
    copy: no
  when: geckodriver.stat.exists == False
  tags:
    - apt

- name: Install dependencies for Firefox 46.0.1.
  apt:
    name: "{{ item }}"
  with_items:
    - libasound2
    - libcairo-gobject2
    - libgtk-3-0
    - libstartup-notification0
  tags:
    - apt

- name: Copy xvfb init script.
  copy:
    src: xvfb
    dest: /etc/init.d/xvfb
    owner: root
    mode: '700'
  tags:
    - xvfb
    - permissions

- name: Update rc.d to run xvfb at boot.
  command: update-rc.d xvfb defaults
  register: xvfb_setup
  changed_when: "'System start/stop links for /etc/init.d/xvfb already exist' not in xvfb_setup.stdout"
  notify: start xvfb
  tags:
    - xvfb

- name: Set DISPLAY environment variable for xvfb.
  copy:
    src: xvfb_display.sh
    dest: /etc/profile.d/xvfb_display.sh
    owner: root
    mode: '444'
  tags:
    - xvfb
    - environment
    - permissions
