---
- name: Check whether Application Server is registered as OSSEC agent.
  command: /var/ossec/bin/list_agents -a
  register: ossec_list_agents_result
  # Read-only task, so don't report changed
  changed_when: false
  tags:
    - ossec_auth

- name: Create OSSEC manager SSL key.
  command: openssl genrsa -out /var/ossec/etc/sslmanager.key 4096
  args:
    creates: /var/ossec/etc/sslmanager.key
  when: ossec_list_agents_result.stdout != "{{ app_hostname }}-{{ app_ip }} is available."
  tags:
    - ossec_auth

- name: Create OSSEC manager SSL certificate.
  command: >
    openssl req -new -x509 -batch
    -subj "/CA=AU/ST=Some-State/locality=city/O=Internet Widgits Pty Ltd/commonName=mon/organizationUnitName=section/emailAddress=admin@localhost"
    -key /var/ossec/etc/sslmanager.key -out /var/ossec/etc/sslmanager.cert -days 365
  args:
    creates: /var/ossec/etc/sslmanager.cert
  when: ossec_list_agents_result.stdout != "{{ app_hostname }}-{{ app_ip }} is available."
  tags:
    - ossec_auth

- name: Check whether IPv4 rules exist on OSSEC manager.
  stat:
    path: /etc/network/iptables/rules_v4
  register: iptables_rules
  notify: add firewall rule exemption for authd
  notify: reload authd iptables
  when: ossec_list_agents_result.stdout != "{{ app_hostname }}-{{ app_ip }} is available."
  tags:
    - ossec_auth
    - iptables

- name: Start authd.
  shell: /var/ossec/bin/ossec-authd -i {{ app_ip }} -p 1515 >/dev/null 2>&1 &
  async: 0
  poll: 0
  when: ossec_list_agents_result.stdout != "{{ app_hostname }}-{{ app_ip }} is available."
  tags:
    - ossec_auth
