---
- name: Create storage package script folder
  file:
    state: directory
    path: /tmp/src_install_files/

- name: Copy app code to build directory.
  synchronize:
    src: "../{{ package_name }}"
    dest: "/tmp/src_install_files/"
    recursive: yes
    delete: yes
    use_ssh_args: "{{ 'yes' if amazon_builder else omit }}"
    rsync_opts: "{{ securedrop_app_rsync_opts }}"

- name: run bash script to build generic packages
  script: "build_generic_package.sh {{ package_name }}"

- name: Track down package
  find:
    path: /tmp
    patterns: "*{{ package_name }}*.deb"
  register: list_deb_pkg_results
  changed_when: false

- name: Fetch back package
  fetch:
    src: "{{ item.path }}"
    dest: "{{ securedrop_local_build }}/"
    flat: yes
  with_items: "{{ list_deb_pkg_results.files }}"
