---
- name: Add cron job to clean SecureDrop tmp dir daily.
  cron:
    name: cleanup SecureDrop temp dir
    job: "{{ securedrop_code }}/manage.py clean-tmp"
    special_time: daily
  tags:
    - cron
