---
# Set the default SSH listening address for the sshd config file.
# In production, sshd listening to localhost (127.0.0.1), since all SSH
# connections are forced over Tor. In staging, this value will be 0.0.0.0
# to enable direct access for testing during development.
ssh_listening_address: 127.0.0.1

allow_direct_access: false

