---
- name: Install dependencies for building securedrop-app-code deb package.
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items: "{{ development_dependencies }}"
  tags: apt

- name: Install pip wheel.
  pip:
    name: wheel
  tags: pip

- name: Install sass Ruby gem
  gem:
    name: sass
    # TODO: This version lock can be removed when if/when we can get Ruby>2
    # installed on the machine that runs this task (see
    # https://github.com/freedomofpress/securedrop/issues/1594).
    version: "3.4.23"
    user_install: no
  sudo: yes

- name: Copy install_files/securedrop-app-code dir to build path.
  synchronize:
    src: ../securedrop-app-code/
    dest: "{{ securedrop_app_code_deb_dir }}"
    delete: yes
    recursive: yes
    use_ssh_args: "{{ 'yes' if amazon_builder else omit }}"

- name: Add rsync-filter for additively including files.
  copy:
    src: rsync-filter
    dest: /tmp/rsync-filter

- debug: var=securedrop_code

- name: Copy app code to build directory.
  synchronize:
    src: ../../securedrop/
    dest: "{{ item.dest }}"
    recursive: yes
    delete: yes
    use_ssh_args: "{{ 'yes' if amazon_builder else omit }}"
    rsync_opts: "{{ item.opts }}"
  with_items:
    - dest: "{{ securedrop_code_raw }}"
      opts: "{{ securedrop_app_rsync_opts }}"
    - dest: "{{ securedrop_code_filtered }}"
      opts: "{{ securedrop_app_rsync_opts+securedrop_app_rsync_filter }}"

- name: Create CSS directory.
  file:
    state: directory
    path: "{{ securedrop_code }}/static/css"

- name: Compile SASS to CSS.
  shell: "/usr/local/bin/sass --force --stop-on-error --update sass:{{ securedrop_code }}/static/css --style compressed"
  args:
    chdir: "{{ securedrop_code_raw }}"

- name: Create pip wheel archive for Debian package requirements.
  command: pip wheel -r {{ securedrop_pip_requirements }} -w {{ securedrop_app_code_deb_dir }}/var/securedrop/wheelhouse
  tags: pip

- name: Create apparmor.d directory in build path.
  file:
    state: directory
    dest: "{{ securedrop_app_code_deb_dir }}/etc/apparmor.d"
  tags: apparmor

- name: Copy AppArmor profiles to build path.
  copy:
    src: "{{ item }}"
    dest: "{{ securedrop_app_code_deb_dir }}/etc/apparmor.d/{{ item }}"
  with_items: "{{ apparmor_profiles }}"
  tags: apparmor

- name: Build securedrop-app-code Debian package.
  command: dpkg-deb --build {{ securedrop_app_code_deb_dir }}

- name: Fetch newly built Debian packages back to localhost.
  fetch:
    src: "{{ securedrop_app_code_deb_dir }}.deb"
    dest: "{{ ossec_build_deb_package_local_dest_dir }}"
    flat: yes
    fail_on_missing: yes
