---
- name: Install sass Ruby gem
  gem:
    name: sass
    # TODO: This version lock can be removed when if/when we can get Ruby>2
    # installed on the machine that runs this task (see
    # https://github.com/freedomofpress/securedrop/issues/1594).
    version: "3.4.23"
    user_install: no
  sudo: yes

- name: Create CSS directory.
  file:
    state: directory
    path: "{{ securedrop_code_filtered }}/static/css"

- name: Copy app code SASS files to build directory.
  synchronize:
    src: ../../securedrop/sass
    dest: "{{ securedrop_code_filtered }}/sass"
    recursive: yes
    delete: yes
    use_ssh_args: "{{ 'yes' if amazon_builder else omit }}"
    rsync_opts: "{{ securedrop_app_rsync_opts }}"

- name: Compile SASS to CSS.
  shell: "/usr/local/bin/sass --force --stop-on-error --update sass:{{ securedrop_code_filtered }}/static/css --style compressed"
  args:
    chdir: "{{ securedrop_code_filtered }}"

  # We only want to ship the generated CSS files; not the SASS source.
- name: Remove temporary SASS directory from package build directory.
  file:
    state: absent
    path: "{{ securedrop_code_filtered }}/sass"
