---
# Check the value of `ssh_users` in site-specific vars to ensure
# we're using a unique username. If the playbook is running with a username
# of e.g. `amnesia`, then the vars file has been configured incorrectly.
- name: Validate Admin username (specified in vars).
  assert:
    that:
      - "ssh_users != item"
      - "ssh_users != ''"
      - "item not in ssh_users"
  with_items: "{{ securedrop_validate_disallowed_users }}"
